version: '3.8'

services:
  assignment-webserver:
    image: atvenu/assignment-webserver:latest
    ports:
      - "9090:8080"
    environment:
      - BORDER_COLOR=blue
    volumes:
      - ./data.csv:/app/data.csv

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  prometheus:

